create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(64) not null,
    status varchar(16) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table app_role (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    name varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table app_user_role (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table knowledge_base (
    id bigint generated by default as identity primary key,
    name varchar(128) not null,
    description varchar(255),
    status varchar(16) not null,
    created_by bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table document_record (
    id bigint generated by default as identity primary key,
    knowledge_base_id bigint not null,
    file_name varchar(255) not null,
    file_type varchar(32) not null,
    object_key varchar(255) not null,
    parse_status varchar(16) not null,
    index_status varchar(16) not null,
    uploaded_by bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_document_record_kb_id on document_record (knowledge_base_id);

create table document_chunk (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    knowledge_base_id bigint not null,
    chunk_no int not null,
    content clob not null,
    token_count int not null,
    start_offset int not null,
    end_offset int not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_document_chunk_kb_id on document_chunk (knowledge_base_id);
create index idx_document_chunk_document_id on document_chunk (document_id);

create table conversation (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    knowledge_base_id bigint not null,
    status varchar(16) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table message_record (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    role varchar(16) not null,
    content clob not null,
    citation_json clob,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_message_record_conversation_id on message_record (conversation_id);

create table ticket (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null,
    title varchar(255) not null,
    description clob not null,
    priority varchar(16) not null,
    status varchar(32) not null,
    assignee_id bigint,
    created_by bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table approval_task (
    id bigint generated by default as identity primary key,
    target_type varchar(32) not null,
    target_id bigint not null,
    approver_id bigint not null,
    status varchar(16) not null,
    comment varchar(255),
    decided_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table audit_log (
    id bigint generated by default as identity primary key,
    actor_id bigint,
    event_type varchar(64) not null,
    target_type varchar(32),
    target_id bigint,
    trace_id varchar(64) not null,
    payload_json clob,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_audit_log_trace_id on audit_log (trace_id);
create index idx_audit_log_target on audit_log (target_type, target_id);
