create table document_index_task (
    id bigint generated by default as identity primary key,
    document_id bigint not null,
    status varchar(16) not null,
    attempt_count int not null,
    max_attempts int not null,
    trace_id varchar(64),
    last_error varchar(512),
    next_run_at timestamp not null,
    started_at timestamp,
    finished_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_document_index_task_due on document_index_task (status, next_run_at, id);
create index idx_document_index_task_document_id on document_index_task (document_id);
