create table auth_token_session (
    id bigint generated by default as identity primary key,
    token_hash varchar(64) not null unique,
    user_id bigint not null,
    username varchar(64) not null,
    role_codes varchar(255) not null,
    issued_at timestamp not null,
    expires_at timestamp not null,
    revoked_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_auth_token_session_user_id on auth_token_session (user_id);
create index idx_auth_token_session_expires_at on auth_token_session (expires_at);
